Improve debug message
docker/v1.10-migrator pull request #22
Opened 2017-07-18 20:28 UTC by blag

to aid in troubleshooting.

2017-07-23 23:27 UTC, thaJeztah requested changes

2017-07-23 23:27 UTC, thaJeztah commented on Godeps/_workspace/src/github.com/docker/docker/daemon/graphdriver/zfs/zfs_linux.go
> +		logrus.Debugf("[zfs] no zfs dataset found for rootdir '%s', found '%s'", rootdir, buf.Type)
This code is vendored from upstream, so has to be changed here; https://github.com/moby/moby/blob/master/daemon/graphdriver/zfs/zfs_linux.go#L18

2017-07-24 07:56 UTC, blag commented on Godeps/_workspace/src/github.com/docker/docker/daemon/graphdriver/zfs/zfs_linux.go
> +		logrus.Debugf("[zfs] no zfs dataset found for rootdir '%s', found '%s'", rootdir, buf.Type)
Thanks. Upstreamed.

2017-07-24 07:56 UTC, blag commented
Upstreamed to moby/moby#34232.

2017-07-24 07:56 UTC, closed without merging